apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: p73yv7c2k-go-gitops
  description: This is GitOps manifest for p73yv7c2k-go   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: p73yv7c2k-go
    backstage.io/kubernetes-id: p73yv7c2k-go 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: p73yv7c2k-go   
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:p73yv7c2k-go
